---
  title: "Step 3: Raw quality plots"
author: "Andrea Estandia"
date: "`r Sys.Date()`"
format: html
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("src", "metabarcoding-gt.R"))
install_required_packages()
```

```{r}

## read in the lists of cutadapt files
fnFs.cut <- readRDS(file.path(LOCUS_DIR, "R_objects", "02_fnFs.cut.rds"))
fnRs.cut <- readRDS(file.path(LOCUS_DIR, "R_objects", "02_fnRs.cut.rds"))

# extract sample names and write to R object
sample.names <- unname(sapply(
  fnFs.cut,
  if (LOCUS == "16s") get.sample.name.16s else get.sample.name
))

saveRDS(sample.names, file = file.path(LOCUS_DIR, 
                                       "R_objects", 
                                       "03_sample_names.rds")
)

## write plot to file for inspection

pdf(file = file.path(LOCUS_DIR, "plots", "pre_trim_quality_plots.pdf"),
      width = 10, 
      height = 10)

## inspect read quality plots
plotQualityProfile(fnFs.cut[1:2])
plotQualityProfile(fnRs.cut[1:2])
dev.off()
```