---
  title: "Step 6: Merge and remove_chimeras.R"
author: "Andrea Estandia"
date: "`r Sys.Date()`"
format: html
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("src", "metabarcoding-gt.R"))
install_required_packages()
```

```{r}
## read in the filt files
filtFs <- readRDS(file.path(LOCUS_DIR, 
                            "R_objects", 
                            "04_fnFs.filtN.rds"))

filtRs <- readRDS(file.path(LOCUS_DIR, 
                            "R_objects", 
                            "04_fnRs.filtN.rds"))

## read in the error models
errF <- readRDS(file.path(LOCUS_DIR, 
                          "R_objects", 
                          "05_errF.rds"))

errR <- readRDS(file.path(LOCUS_DIR, 
                          "R_objects", 
                          "05_errR.rds"))

## check files exist
exists <- file.exists(filtFs)

## dereplicate the reads
derepFs <- derepFastq(filtFs[exists])
derepRs <- derepFastq(filtRs[exists])

# get sample names
sample.names <- 
  readRDS(file.path(LOCUS_DIR, 
                    "R_objects", 
                    "03_sample_names.rds"))

## name the derep class objects
names(derepFs) <- sample.names[exists]
names(derepRs) <- sample.names[exists]

## perform dada2 sample inference
dadaFs <- dada(derepFs, err = errF, multithread=TRUE)
dadaRs <- dada(derepRs, err = errR, multithread=TRUE)

## merge paired reads
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)

## make ASV table
seqtab <- makeSequenceTable(mergers)

## remove chimeras
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)

## write out ASV sequences
sequences <- colnames(seqtab.nochim)
headers <- vector(dim(seqtab.nochim)[2], mode="character")

for (i in 1:dim(seqtab.nochim)[2]) {
  headers[i] <- paste(">ASV", i, sep="_")
}

output_fasta <- c(rbind(headers, sequences))

write(output_fasta, file.path(LOCUS_DIR, "outputs", paste0("06_", LOCUS, "ASV_seqs.fasta")))


#####################


# write out ASV counts
tab <- t(seqtab.nochim)

write.table(tab, 
            file.path(LOCUS_DIR, 
                      "outputs", 
                      paste0("06_", 
                             LOCUS, 
                             "ASV_counts.tsv")), 
            sep="\t",
            quote=F, 
            col.names=NA)

saveRDS(dadaFs, file = file.path(LOCUS_DIR, 
                      "R_objects", "06_dadaFs.rds"))
saveRDS(dadaRs, file.path(LOCUS_DIR, 
                      "R_objects",
                      "06_dadaRs.rds"))
saveRDS(mergers, file.path(LOCUS_DIR, 
                      "R_objects",
                      "06_mergers.rds"))
saveRDS(seqtab.nochim, 
        file = file.path(LOCUS_DIR, 
                      "R_objects", 
                      "06_seqtab.nochim.rds"))


# Transpose so samples are rows
seqtab.nochim.t <- t(seqtab.nochim)

# Iterate over each sample and write its ASVs to a separate FASTA
for (sample in colnames(seqtab.nochim.t)) {
  sample_counts <- seqtab.nochim.t[, sample]
  present_seqs <- names(sample_counts[sample_counts > 0])
  
  if (length(present_seqs) > 0) {
    # Create unique ASV headers for each sequence
    headers <- paste0(">", sample, "_ASV", seq_along(present_seqs))
    
    # Interleave headers and sequences
    fasta_lines <- c(rbind(headers, present_seqs))
    
    # Write to FASTA file
    write(fasta_lines, 
          file = file.path(LOCUS_DIR, "outputs",
                           "fasta_asv",
                           paste0(sample, "_ASVs.fasta")))
  }
}
```

```{r}
seqtab.nochim <- readRDS(seqtab.nochim,
        file = file.path(LOCUS_DIR,
                      "R_objects",
                      "06_seqtab.nochim.rds"))
```

Contamination report
```{r}
# 1. Find Neg rows
neg_rows <- grep("^Neg", rownames(seqtab.nochim))
neg_data <- seqtab.nochim[neg_rows, , drop = FALSE]

# 1a. Filter out negatives with less than 500 reads
neg_data <- neg_data[rowSums(neg_data) >= 1000, , drop = FALSE]

# 2. Find ASVs appearing in filtered negatives
neg_asvs <- colnames(seqtab.nochim)[colSums(neg_data > 0) > 0]

# 3. Subset full table to ASVs in negatives
seqtab_negs_present <- seqtab.nochim[, neg_asvs, drop = FALSE]

# 4. Identify real (non-negative) samples
nonneg_rows <- setdiff(rownames(seqtab.nochim), rownames(neg_data))
nonneg_data <- seqtab_negs_present[nonneg_rows, , drop = FALSE]

# 5. Split samples into contaminated and clean
samples_with_shared_asvs <- rownames(nonneg_data)[rowSums(nonneg_data > 0) > 0]
samples_clean <- setdiff(nonneg_rows, samples_with_shared_asvs)

# 6. Build summary for contaminated samples
summary_list <- lapply(samples_with_shared_asvs, function(sample) {
  sample_counts <- nonneg_data[sample, , drop = FALSE]
  shared_asvs <- colnames(sample_counts)[sample_counts > 0]
  
  # Total reads in the sample
  total_sample_reads <- sum(seqtab.nochim[sample, ])
  
  # Total reads in the negative(s) for these ASVs
  total_neg_reads <- sum(neg_data[, shared_asvs, drop = FALSE])
  
  # Fraction of sample reads contributed by negative reads
  reads_shared_relative <- total_neg_reads / total_sample_reads
  
  # Names of negatives that share ASVs
  negs_sharing <- rownames(neg_data)[rowSums(neg_data[, shared_asvs, drop = FALSE] > 0) > 0]
  
  data.frame(
    Sample = sample,
    Total_Reads_Sample = total_sample_reads,
    Total_Reads_Negative = total_neg_reads,
    Reads_Shared_Relative = reads_shared_relative,
    Negatives_Shared = paste(negs_sharing, collapse = ", "),
    Contamination = "contaminated"
  )
})

# 7. Build summary for clean samples
clean_list <- lapply(samples_clean, function(sample) {
  total_sample_reads <- sum(seqtab.nochim[sample, ])
  
  data.frame(
    Sample = sample,
    Total_Reads_Sample = total_sample_reads,
    Total_Reads_Negative = 0,
    Reads_Shared_Relative = 0,
    Negatives_Shared = "",
    Contamination = "clean"
  )
})

# 8. Combine and sort
summary_df <- do.call(rbind, c(summary_list, clean_list))
summary_df_sorted <- summary_df[order(-summary_df$Reads_Shared_Relative), ]
rownames(summary_df_sorted) <- NULL

# 9. Save to CSV
write.csv(summary_df_sorted, file.path(LOCUS_DIR, "outputs", paste0(LOCUS, "_contamination_report_simple.csv")), row.names = FALSE)

# View result
summary_df_sorted

```

Identify potentially contaminated samples
```{r}
# 1. Identify contaminated samples
contaminated_samples <- summary_df_sorted %>%
  filter(Contamination == "contaminated") %>%
  pull(Sample)

# 2. Prepare table to store relative contribution per sample
reads_from_negatives <- data.frame(
  Sample = contaminated_samples,
  Neg_Reads_in_Sample = numeric(length(contaminated_samples)),
  Relative_Contribution = numeric(length(contaminated_samples))
)

# 3. Loop through each contaminated sample
for (i in seq_along(contaminated_samples)) {
  sample_name <- contaminated_samples[i]
  
  # ASVs in negatives contributing to this sample
  negs_sharing <- summary_df_sorted %>%
    filter(Sample == sample_name) %>%
    pull(Negatives_Shared) %>%
    strsplit(", ") %>%
    unlist()
  
  # ASVs present in these negatives
  asvs_in_neg <- colnames(seqtab.nochim)[colSums(seqtab.nochim[rownames(seqtab.nochim) %in% negs_sharing, , drop = FALSE]) > 0]
  
  # Reads in the sample for these ASVs
  reads_shared <- sum(seqtab.nochim[sample_name, asvs_in_neg])
  
  # Total reads in the sample
  total_reads_sample <- sum(seqtab.nochim[sample_name, ])
  
  # Store counts and relative contribution
  reads_from_negatives$Neg_Reads_in_Sample[i] <- reads_shared
  reads_from_negatives$Total_Reads_in_Sample[i] <-total_reads_sample
  reads_from_negatives$Relative_Contribution[i] <- round(reads_shared / total_reads_sample, digits = 4)
}

remove_samples <-
  reads_from_negatives %>% 
  filter(Relative_Contribution>0.05) %>%
  pull(Sample)

```

Write ASV fasta without contaminated negatives and remove samples for which the relative contribution of negative reads is more than 5%
```{r}
# 1. Identify samples to remove (low contamination)
remove_samples <- reads_from_negatives %>%
  filter(Relative_Contribution > 0.05) %>%
  pull(Sample)

# 2. Identify contaminated negatives
contaminated_negatives <- summary_df_sorted %>%
  filter(Contamination == "contaminated") %>%
  distinct(Negatives_Shared) %>%
  pull(Negatives_Shared) %>%
  strsplit(", ") %>%
  unlist() %>%
  unique()

# 3. Combine samples to remove: low-contamination samples + contaminated negatives
samples_to_exclude <- unique(c(remove_samples, contaminated_negatives))

# 4. Find ASVs in contaminated negatives
contaminating_asvs <- colnames(seqtab.nochim)[colSums(seqtab.nochim[rownames(seqtab.nochim) %in% contaminated_negatives, , drop = FALSE]) > 0]

# 5. Remove contaminating ASVs from contaminated samples
contaminated_samples <- summary_df_sorted %>%
  filter(Contamination == "contaminated") %>%
  pull(Sample)

seqtab_clean <- seqtab.nochim
seqtab_clean[contaminated_samples, contaminating_asvs] <- 0  # set contaminating ASVs to 0

# 6. Create output FASTA (skip samples_to_exclude)
asv_seqs <- colnames(seqtab_clean)
asv_headers <- paste0(">ASV_", seq_len(ncol(seqtab_clean)))

output_lines <- character()

for (sample_idx in seq_len(nrow(seqtab_clean))) {
  sample_name <- rownames(seqtab_clean)[sample_idx]
  
  # skip samples to exclude
  if (sample_name %in% samples_to_exclude) next
  
  counts <- seqtab_clean[sample_name, ]
  present <- which(counts > 0)
  
  for (i in present) {
    header <- paste0(">ASV_", i, ";sample=", sample_name)
    seq <- asv_seqs[i]
    output_lines <- c(output_lines, header, seq)
  }
}

# 7. Write to FASTA
writeLines(output_lines, file.path(LOCUS_DIR, "outputs", paste0("06_", LOCUS, "_ASV_seqs.fasta")))

```

Create reads style fasta file to create mapping reads tables 
```{r}
# 1. Identify samples to remove (low contamination)
remove_samples <- reads_from_negatives %>%
  filter(Relative_Contribution < 0.05) %>%  # low contamination
  pull(Sample)

# 2. Identify contaminated negatives
contaminated_negatives <- summary_df_sorted %>%
  filter(Contamination == "contaminated") %>%
  distinct(Negatives_Shared) %>%
  pull(Negatives_Shared) %>%
  strsplit(", ") %>%
  unlist() %>%
  unique()

# 3. Combine samples to exclude
samples_to_exclude <- unique(c(remove_samples, contaminated_negatives))

# 4. Find ASVs in contaminated negatives
contaminating_asvs <- colnames(seqtab.nochim)[colSums(seqtab.nochim[rownames(seqtab.nochim) %in% contaminated_negatives, , drop = FALSE]) > 0]

# 5. Remove contaminating ASVs from contaminated samples
contaminated_samples <- summary_df_sorted %>%
  filter(Contamination == "contaminated") %>%
  pull(Sample)

seqtab_clean <- seqtab.nochim
seqtab_clean[contaminated_samples, contaminating_asvs] <- 0  # set contaminating ASVs to 0

# 6. Create reads-style FASTA
asv_seqs <- colnames(seqtab_clean)  # sequences are stored as column names
output_lines <- character()
read_counter <- 1

for (sample_idx in seq_len(nrow(seqtab_clean))) {
  sample_name <- rownames(seqtab_clean)[sample_idx]
  
  # skip samples to exclude
  if (sample_name %in% samples_to_exclude) next
  
  counts <- seqtab_clean[sample_name, ]
  present <- which(counts > 0)
  
  for (i in present) {
    seq <- asv_seqs[i]
    n_reads <- counts[i]
    
    for (r in seq_len(n_reads)) {
      header <- paste0(">readsequence", read_counter, ";sample=", sample_name)
      output_lines <- c(output_lines, header, seq)
      read_counter <- read_counter + 1
    }
  }
}

# 7. Write to FASTA
writeLines(output_lines, file.path(LOCUS_DIR, "outputs", paste0("06_", LOCUS, "_reads_style.fasta")))


```

